spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-rds.yml

server:
  port: 4000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /center
  tomcat:
    threads:
      max: 200
    connection-timeout: 10s
    keep-alive-timeout: 10s
    max-keep-alive-requests: 200
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB

spring:
  application:
    name: pilathy-api-center
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm
    servlet:
      load-on-startup: 1
